<?php if ($wo['loggedin'] == true) { ?>

<?php /*?><div class="sidebar-conatnier">
  <div class="sidebar">
    <div class="home profile-style main sidebar-profile-style">
      <div class="card hovercard">
        <div class="cardheader"> <img src="<?php echo $wo['user']['cover']?>" id="cover-image" alt="<?php echo $wo['user']['name']?> Cover Image"> </div>
        <div class="avatar"> <img id="updateImage-<?php echo $wo['user']['user_id']?>" alt="<?php echo $wo['user']['name']?> Profile Picture" src="<?php echo $wo['user']['avatar']?>"> </div>
        <div class="info">
          <div class="title"> <a id="user-full-name" data-ajax="?link1=timeline&u=<?php echo $wo['user']['username'];?>" href="<?php echo $wo['user']['url'];?>"><?php echo $wo['user']['name']?></a>
            <?php //if($wo['user']['verified'] == 1):?>
            <i class="fa fa-check-circle verified-color" data-toggle="tooltip" title="<?php echo $wo['lang']['verified_user'];?>"></i>
            <?php //endif;?>
          </div>
        </div>
      </div>
    </div>
  </div>
</div><?php */?>
<?php /*?><div class="left-sidebar">
  <ul>
    <li><a href="<?php echo $wo['user']['url']; ?>" data-ajax="?link1=timeline&u=<?php echo $wo['user']['username'];?>"><img class="sidebar-icon" src="<?php echo Wo_GetIcon('user-3'); ?>" alt="user-3"><?php echo $wo['lang']['my_profile'];?></a></li>
    <li><a href="<?php echo Wo_SeoLink('index.php?link1=messages'); ?>" data-ajax="?link1=messages"><img class="sidebar-icon" src="<?php echo Wo_GetIcon('paper-plane-1'); ?>" alt="paper-plane"><?php echo $wo['lang']['messages'];?></a></li>
    <li><a href="<?php echo Wo_SeoLink('index.php?link1=setting'); ?>" data-ajax="?link1=setting"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('settings-4'); ?>" alt="settings"><?php echo $wo['lang']['setting'];?></a></li>
    <!--<li>
      <hr>
    </li>-->
    <?php if (Wo_CanBlog() == true) { ?>
     <li><a href="<?php echo Wo_SeoLink('index.php?link1=my-blogs'); ?>" data-ajax="?link1=my-blogs"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('notebook-2'); ?>" alt="notebook-3"><?php echo $wo['lang']['my_articles'] ?></a></li>
    <?php } ?>
    <?php if ($wo['config']['groups'] == 1) { ?>
    <li><a href="<?php echo Wo_SeoLink('index.php?link1=groups'); ?>" data-ajax="?link1=groups"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('users-1'); ?>" alt="users-1"><?php echo $wo['lang']['groups'];?></a></li>
    <?php } ?>
    <?php if ($wo['config']['pages'] == 1) { ?>
    <li><a href="<?php echo Wo_SeoLink('index.php?link1=pages'); ?>" data-ajax="?link1=pages"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('flag-2'); ?>" alt="flag-2"><?php echo $wo['lang']['pages'];?></a></li>
    <?php } ?>
    <li><a href="<?php echo Wo_SeoLink('index.php?link1=albums'); ?>" data-ajax="?link1=albums"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('picture-2'); ?>" alt="picture-2"><?php echo $wo['lang']['albums'];?></a></li>
    <?php if ($wo['config']['classified'] == 1) { ?>
    <li><a href="<?php echo Wo_SeoLink('index.php?link1=my-products'); ?>" data-ajax="?link1=my-products"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('shopping-cart'); ?>" alt="shopping-cart"><?php echo $wo['lang']['my_products'];?></a></li>
    <?php } ?>
    <!--<li>
      <hr>
    </li>-->
    <?php if ($wo['config']['games'] == 1) { ?>
    <!-- <li><a href="<?php echo Wo_SeoLink('index.php?link1=games'); ?>" data-ajax="?link1=games"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('app'); ?>" alt="app"><?php echo $wo['lang']['games'];?></a></li>-->
    <?php } ?>
    <!--<li>
      <hr>
    </li>-->
    <li><a href="<?php echo Wo_SeoLink('index.php?link1=saved-posts');?>" data-ajax="?link1=saved-posts"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('medal'); ?>" alt="medal"><?php echo $wo['lang']['saved_posts'];?></a></li>
      <li><a href="<?php echo Wo_SeoLink('index.php?link1=search?query=');?>"><img class="sidebar-icon" src="<?php echo Wo_GetIcon('search'); ?>" alt="search"><?php echo $wo['lang']['explore'];?></a></li>
    <?php if ($wo['config']['blogs'] == 1) { ?>
    <!--<li>
      <hr>
    </li>
    <li><a href="<?php echo Wo_SeoLink('index.php?link1=blogs'); ?>"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('document'); ?>" alt="document"><?php echo $wo['lang']['blog'] ?></a></li>-->
    <?php } ?>
    <?php if ($wo['config']['events'] == 1) { ?>
    <!-- <li> <a href="<?php echo Wo_SeoLink('index.php?link1=events'); ?>"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('calendar'); ?>" alt="calendar"><?php echo $wo['lang']['events'] ?></a> </li>-->
    <?php } ?>
    <?php if ($wo['config']['forum'] == 1) { ?>
    <li>
      <hr>
    </li>
    <li><a href="<?php echo Wo_SeoLink('index.php?link1=forum'); ?>"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('chatting'); ?>" alt="chatting"><?php echo $wo['lang']['forum'];?></a></li>
    <?php } ?>
    <?php if ($wo['config']['classified'] == 1) { ?>
    <li><a href="<?php echo Wo_SeoLink('index.php?link1=products'); ?>"><img class="sidebar-icon"  src="<?php echo Wo_GetIcon('store'); ?>" alt="store"><?php echo $wo['lang']['market'];?></a></li>
    <?php } ?>
    <?php if ($wo['config']['movies'] == 1) { ?>
     <li><a href="<?php echo Wo_SeoLink('index.php?link1=movies'); ?>"><img class="sidebar-icon" src="<?php echo Wo_GetIcon('video-player-1'); ?>" alt="video-player-1"><?php echo $wo['lang']['movies'];?></a></li>
    <?php } ?>
    <?php if ($wo['config']['find_friends'] == 1) { ?>
    <li><a href="<?php echo Wo_SeoLink('index.php?link1=friends-nearby'); ?>"><img class="sidebar-icon" src="<?php echo Wo_GetIcon('placeholder'); ?>" alt="placeholder"><?php echo $wo['lang']['find_friends'];?></a></li>
    <?php } ?>
    <?php if(!empty($wo['plugin_list']['plugin_menu'])){?>
    <!--<li>
      <hr>
    </li>-->
    <?php echo Wo_LoadPage('plugins/plugin_menu');} ?>
    <?php if ($wo['user']['is_pro'] == 0 && $wo['config']['pro'] == 1) { ?>
    <li>
      <hr>
    </li>
    <li><a href="<?php echo Wo_SeoLink('index.php?link1=go-pro');?>"><i class="fa fa-arrow-down fa-fw"></i><?php echo $wo['lang']['put_me_here'];?></a></li>
    <?php } ?>
  </ul>
  <?php if ($wo['config']['pro'] == 1) { ?>
  <div class="featured-users">
    <ul class="list-inline">
      <?php 

          $users = Wo_FeaturedUsers(9);

          ?>
      <?php 

          foreach ($users as $wo['user-list']) {

              echo Wo_LoadPage('home/user-list');

          }

          ?>
    </ul>
  </div><br>
  <?php } ?>
</div>
<br><?php */?>
<?php 
global $sqlConnect;
$query_oneNotice = mysqli_query($sqlConnect, "SELECT * FROM tbl_notice_post WHERE `status` = '1'  ORDER BY id desc");
if(mysqli_num_rows($query_oneNotice)>0){ 
?>
<ul class="list-group trending">
  <li class="list-group-item" contenteditable="false"><i class="fa fa-bolt fa-fw"></i> Notices</li>
<?php while($getNoticeInfoVal = mysqli_fetch_array($query_oneNotice)){ ?>
  <li class="list-group-item" dir="auto"> <a href="http://myrwa.co/notice-board/">#<?php echo ucwords($getNoticeInfoVal['notice_title']);?></a> </li>
<?php } ?>  
  <li>
    <div class="clear"></div>
  </li>
</ul>
<?php } ?>

<?php 
global $sqlConnect;
$query_oneDocument = mysqli_query($sqlConnect, "SELECT * FROM tbl_document_directory WHERE `status` = '1'  ORDER BY id desc");
if(mysqli_num_rows($query_oneDocument)>0){ 
?>
<ul class="list-group trending">
  <li class="list-group-item" contenteditable="false"><i class="fa fa-clipboard fa-fw"></i> Documents</li>
<?php while($getDocumentInfoVal = mysqli_fetch_array($query_oneDocument)){ ?>
  <li class="list-group-item" dir="auto"> <a href="http://myrwa.co/document/">#<?php echo ucwords($getDocumentInfoVal['document_tilte']);?></a> </li>
<?php } ?>  
  <li>
    <div class="clear"></div>
  </li>
</ul>
<?php } ?>
<div class="widget">
      <div id="carousel-demo" class="carousel slide" data-ride="carousel">
 <!-- Sliding images statring here -->
  <div class="carousel-inner">
  <?php 
   $AdsI=1;
   global $sqlConnect;
    $query_one      = mysqli_query($sqlConnect, "SELECT * FROM tbl_ads_management_directory WHERE `status` = '1' and `ads_banner_size` = '300X300'   and `ads_banner_position` = 'Left' ORDER BY RAND()");
   while($fetched_data = mysqli_fetch_array($query_one))
   { ?>
   <div class="item <?php if($AdsI==1){?>active <?php } ?>">
   <?php if($fetched_data['ads_banner_type']=="Image"){?>
     <img src="http://myrwa.co/RWAVendor/ads_managements/<?php echo $fetched_data['ads_management_file'];?>" alt="<?php echo $fetched_data['ads_management_tilte'];?>" title="<?php echo $fetched_data['ads_management_tilte'];?>">
     <?php } ?>
   <?php if($fetched_data['ads_banner_type']=="GoogleAd"){ echo $fetched_data['google_ads']; } ?>
   </div>
<?php $AdsI++;  } ?>

 </div>
 <!-- Next / Previous controls here -->
 <a class="left carousel-control" href="#carousel-demo" data-slide="prev">
  <img src="http://myrwa.co/nirwana-img/pre.png"> 
 </a>
 <a class="right carousel-control" href="#carousel-demo" data-slide="next">
  <img src="http://myrwa.co/nirwana-img/next.png">
 </a>

 </div>
    </div>
<?php } ?>