<div class="welcome-footer"> 
<a  href="http://palmterracesselect.com/cms/terms-of-service/"><?php echo $wo['lang']['terms_of_use'];?></a> <a  href="http://nirwanacountry.com/cms/privacy-policy/"><?php echo $wo['lang']['privacy_policy'];?></a> 
<a  href="http://palmterracesselect.com/"><?php echo $wo['lang']['contact_us'];?></a> 
<a  href="http://palmterracesselect.com/cms/about-company/"><?php echo $wo['lang']['about'];?></a>
  <?php  if ($wo['config']['blogs'] == 1) { ?>
 <!-- <a href="<?php echo Wo_SeoLink('index.php?link1=blogs');?>"><?php echo $wo['lang']['blog'];?></a>-->
  <?php } ?>
  <?php

               $pages = Wo_GetCustomPages();

               if (count($pages) > 0) {

                  foreach ($pages as $key => $page) {

                  ?>
 <!-- <a href="<?php echo Wo_SeoLink('index.php?link1=site-pages&page_name=' . $page['page_name']);?>"><?php echo $page['page_title'];?></a>-->
  <?php

                 }

               }

               ?>
  <?php /*?><span class="dropdown dropup"> <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> <i class="fa fa-language"></i> <?php echo $wo['lang']['language'];?> <span class="caret"></span> </a>
  <ul class="dropdown-menu" role="menu" style="width: 60px; min-width: 80px; font-size: 12px;">
    <?php

               $langs = Wo_LangsNamesFromDB();

               if (count($langs) > 0) {

                   foreach ($langs as $key => $wo['langs']) {

                     $language = $wo['langs'];

                     $languages_name = ucfirst($wo['langs']);

                     $link = ($wo['config']['seoLink'] == 1) ? '?lang=' . $language: '?&lang=' . $language;

                ?>
    <li><a class="lang" href="<?php echo $link;?>" rel="nofollow"><?php echo $languages_name;?></a></li>
    <?php } } ?>
  </ul>
  </span><?php */?> </div>
<div class="welcome-footer-right">
<p>Copyright &copy; <?php echo date('Y');?><a href="http://innovatuslimited.com/" target="_blank" style="color:#37a000;"> Innovatus Technologies Pvt. Ltd.</a> All rights reserved.</p>
  <?php 

       /*  $copy = str_replace('{site_name}', $wo['config']['siteName'], $wo['lang']['copyrights']);

         echo $copy = str_replace('{date}', date('Y'), $copy);*/

         ?>
</div>
